[package]
name = "html-cleaner"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3"
htmlize = { version = "1", features = ["unescape"] }
regex = "1"
